name: Run Parser UnitTests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'ovos_date_parser/version.py'
      - 'requirements/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'ovos_date_parser/version.py'
      - 'requirements/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  py_build_tests:
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
    with:
      python_version: "3.8"

  unit_tests:
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, "3.10", "3.11" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev
          python -m pip install build wheel
      - name: Install test dependencies
        run: |
          sudo apt install libssl-dev
          pip install pytest pytest-timeout pytest-cov
      - name: Install repo
        run: |
          pip install ovos-config
          pip install -e .
      - name: Run parse unittests
        run: |
          pytest --cov=ovos_date_parser --cov-report xml test/parse_tests

      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          fail_ci_if_error: true
          files: ./coverage.xml,!./cache
          flags: parsetests
          name: codecov-unittests
          verbose: true
